version: '3.7'
services:
  node-app:
    build: ./gate-simulator
    image: node-app:1.0
    container_name: node-container
    ports:
      - '9999:9999'
  postgres:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=app
      - POSTGRES_DB=app
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass